pool:
  name: Hosted VS2017
  
trigger: none

# Configure this to run for both Debug and Release configurations
strategy:
  matrix:
    debug:
      BuildConfiguration: Debug
    release:
      BuildConfiguration: Release    

variables: 
  RestoreBuildProjects: '**/*.sln'
    # Projects to be run unit tests for
  TestProjects: '**/*[Tt]ests/*.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(RestoreBuildProjects)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'

